# Generated by Django 4.0.5 on 2022-07-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_videoproduct_video_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproduct',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
