# Generated by Django 4.0.5 on 2022-07-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_videoproduct_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproduct',
            name='timestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
